PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX dcterms: <http://purl.org/dc/terms/>

SELECT ?term ?predicate WHERE {
  GRAPH <http://purl.obolibrary.org/obo/vivotest.owl> {
    ?term ?predicate ?value .
  }
  FILTER(isIRI(?term))
  FILTER(STRSTARTS(STR(?predicate), STR(dc:)))
}