PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX IAO: <http://purl.obolibrary.org/obo/IAO_>

SELECT ?entity WHERE {
  GRAPH <http://purl.obolibrary.org/obo/vivotest.owl> {
    ?entity owl:deprecated true .
    FILTER NOT EXISTS { ?entity IAO:0100001 ?replacement }
    FILTER NOT EXISTS { ?entity <http://www.geneontology.org/formats/oboInOwl#consider> ?c }
  }
  FILTER(isIRI(?entity))
}
ORDER BY ?entity
