PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?term ?value WHERE {
  GRAPH <http://purl.obolibrary.org/obo/vivotest.owl> {
    ?term rdfs:label ?value .
  }
  FILTER(isIRI(?term))
  FILTER(REGEX(?value, "https?:"))
}